In [18]:
# 数据清洗:处理缺失值,重复值,异常值
import pandas as pd
pd.set_option('display.min_rows', 30)
# 读取数据
df = pd.read_csv('data/sales_data_500.csv')

df.head()

# 2.数据清洗
# 2.1缺失值处理
df.isnull() # 查看缺失值

# 2.1.1删除缺失值所在行
# df.dropna()
# df = df.dropna(axis=1) # 删除缺失值所在列 0:行 1:列

# 2.1.2填充缺失值
df.fillna("--")
df.ffill() # 填充上一行的值
df.bfill() # 填充下一行的值

           订单号  产品类别  产品名称  销售数量    单价 客户所在城市  支付方式        订单日期
0    890779946  电子产品    手机     4   499     武汉  微信支付  2025-10-22
1    200604502    图书    教材    -7   199     成都   支付宝  2025.10.08
2    550455977    图书  考试资料     9   -15     成都  京东白条  2025-10-15
3    398362082    图书   工具书     3    15     郑州   银行卡  2025/10/07
4    398362082  家居用品    枕头     7   -29     深圳   银行卡  2025/12/09
5    692749116  电子产品    键盘     2  4999     长沙   支付宝  2025-11-27
6    810026086    图书    绘本     4   199     长沙   支付宝  2025-10-25
7    586845604  家居用品    枕头     2    59     长沙   银行卡  2025-12-27
8    853573823  家居用品    被子     6   129     成都   银行卡  2025-12-21
9    596348124  电子产品   钢化膜     9   299     武汉  微信支付  2025-11-09
10   964411347    图书    漫画     1    79     武汉   支付宝  2025-11-13
11   803771909  家居用品    枕头    10    59     苏州  微信支付  2025-11-13
12   678722458    食品    饼干     3    39     武汉  京东白条  2025-11-24
13   248532577    图书    传记     7   199     天津  微信支付  2025-12-16
14   740389325  电子产品    手机     3   199     南京    花呗  2025-10-13
..         ...   ...   ...   ...   ...    ...   ...         ...
485  804503060  电子产品   数据线     6   499     西安   银行卡  2025-12-21
486  964823687  家居用品    台灯     9    39     武汉   支付宝  2025-12-13
487  549431487  家居用品    被子     8    19     重庆   银行卡  2025-11-13
488  836928463  电子产品   钢化膜     4  5999     苏州  微信支付  2025-12-21
489  294493146    食品    咖啡     5   129     南京  京东白条  2025-11-04
490  802693852    食品    饼干     9    39     南京   银行卡  2025-10-08
491  379773344  家居用品    台灯     7    89     苏州   银行卡  2025-12-10
492  766422911    食品    面包     1    89     合肥  京东白条  2025-10-16
493  543570539    服装   西装裤     7    59     厦门   银行卡  2025-10-28
494  591313587    服装   连衣裙     6   129     郑州  京东白条  2025-10-11
495  781288086    服装   牛仔裤     6   499     南京   银行卡  2025-10-01
496  625679392    食品   方便面     3    25     合肥  微信支付  2025-10-05
497  511582876    图书    传记     7    99     郑州    花呗  2025-10-02
498  304630191    图书    漫画     1    79     苏州  京东白条  2025-10-22
499  210282113  电子产品    耳机     6   399     重庆  微信支付  2025-11-17

[500 rows x 8 columns]

In [25]:
# 2.2重复值处理
# 2.2.1查看重复值
df.duplicated() # 所有列重复都重复
df.duplicated(subset=['订单号']) #查看指定列重复

# 2.2.2删除重复值
df.drop_duplicates(subset = ['订单号']) #keep = 'first'保留第一个 'last'最后一个

           订单号  产品类别  产品名称  销售数量    单价 客户所在城市  支付方式        订单日期
0    890779946  电子产品    手机     4   499     武汉  微信支付  2025-10-22
1    200604502    图书    教材    -7   199    NaN   支付宝  2025.10.08
2    550455977    图书  考试资料     9   -15     成都  京东白条  2025-10-15
3    398362082    图书   工具书     3    15     郑州   银行卡  2025/10/07
5    692749116  电子产品    键盘     2  4999     长沙   支付宝  2025-11-27
6    810026086    图书    绘本     4   199    NaN   支付宝  2025-10-25
7    586845604  家居用品    枕头     2    59     长沙   银行卡  2025-12-27
8    853573823  家居用品    被子     6   129     成都   银行卡  2025-12-21
9    596348124  电子产品   钢化膜     9   299     武汉  微信支付  2025-11-09
10   964411347    图书    漫画     1    79     武汉   支付宝  2025-11-13
11   803771909  家居用品    枕头    10    59     苏州  微信支付  2025-11-13
12   678722458    食品    饼干     3    39     武汉  京东白条  2025-11-24
13   248532577    图书    传记     7   199     天津  微信支付  2025-12-16
14   740389325  电子产品    手机     3   199     南京    花呗  2025-10-13
15   112327652    食品   矿泉水     9    89     西安  京东白条  2025-12-24
..         ...   ...   ...   ...   ...    ...   ...         ...
485  804503060  电子产品   数据线     6   499     西安   银行卡  2025-12-21
486  964823687  家居用品    台灯     9    39     武汉   支付宝  2025-12-13
487  549431487  家居用品    被子     8    19     重庆   银行卡  2025-11-13
488  836928463  电子产品   钢化膜     4  5999     苏州  微信支付  2025-12-21
489  294493146    食品    咖啡     5   129     南京  京东白条  2025-11-04
490  802693852    食品    饼干     9    39     南京   银行卡  2025-10-08
491  379773344  家居用品    台灯     7    89     苏州   银行卡  2025-12-10
492  766422911    食品    面包     1    89     合肥  京东白条  2025-10-16
493  543570539    服装   西装裤     7    59     厦门   银行卡  2025-10-28
494  591313587    服装   连衣裙     6   129     郑州  京东白条  2025-10-11
495  781288086    服装   牛仔裤     6   499     南京   银行卡  2025-10-01
496  625679392    食品   方便面     3    25     合肥  微信支付  2025-10-05
497  511582876    图书    传记     7    99     郑州    花呗  2025-10-02
498  304630191    图书    漫画     1    79     苏州  京东白条  2025-10-22
499  210282113  电子产品    耳机     6   399     重庆  微信支付  2025-11-17

[499 rows x 8 columns]

In [30]:
# 2.3异常值处理
# 2.3.1查看异常值
df[df["单价"]<0]
df[df["销售数量"]<0]

# 2.3.2删除异常值
df.drop(df[df["销售数量"]<0].index)
df.drop(df[df["单价"]<0].index)

# 2.3.3 修复异常值
df['单价'] = df['单价'].abs() # 取绝对值
df

           订单号  产品类别  产品名称  销售数量    单价 客户所在城市  支付方式        订单日期
0    890779946  电子产品    手机     4   499     武汉  微信支付  2025-10-22
1    200604502    图书    教材    -7   199    NaN   支付宝  2025.10.08
2    550455977    图书  考试资料     9    15     成都  京东白条  2025-10-15
3    398362082    图书   工具书     3    15     郑州   银行卡  2025/10/07
4    398362082  家居用品    枕头     7    29     深圳   银行卡  2025/12/09
5    692749116  电子产品    键盘     2  4999     长沙   支付宝  2025-11-27
6    810026086    图书    绘本     4   199    NaN   支付宝  2025-10-25
7    586845604  家居用品    枕头     2    59     长沙   银行卡  2025-12-27
8    853573823  家居用品    被子     6   129     成都   银行卡  2025-12-21
9    596348124  电子产品   钢化膜     9   299     武汉  微信支付  2025-11-09
10   964411347    图书    漫画     1    79     武汉   支付宝  2025-11-13
11   803771909  家居用品    枕头    10    59     苏州  微信支付  2025-11-13
12   678722458    食品    饼干     3    39     武汉  京东白条  2025-11-24
13   248532577    图书    传记     7   199     天津  微信支付  2025-12-16
14   740389325  电子产品    手机     3   199     南京    花呗  2025-10-13
..         ...   ...   ...   ...   ...    ...   ...         ...
485  804503060  电子产品   数据线     6   499     西安   银行卡  2025-12-21
486  964823687  家居用品    台灯     9    39     武汉   支付宝  2025-12-13
487  549431487  家居用品    被子     8    19     重庆   银行卡  2025-11-13
488  836928463  电子产品   钢化膜     4  5999     苏州  微信支付  2025-12-21
489  294493146    食品    咖啡     5   129     南京  京东白条  2025-11-04
490  802693852    食品    饼干     9    39     南京   银行卡  2025-10-08
491  379773344  家居用品    台灯     7    89     苏州   银行卡  2025-12-10
492  766422911    食品    面包     1    89     合肥  京东白条  2025-10-16
493  543570539    服装   西装裤     7    59     厦门   银行卡  2025-10-28
494  591313587    服装   连衣裙     6   129     郑州  京东白条  2025-10-11
495  781288086    服装   牛仔裤     6   499     南京   银行卡  2025-10-01
496  625679392    食品   方便面     3    25     合肥  微信支付  2025-10-05
497  511582876    图书    传记     7    99     郑州    花呗  2025-10-02
498  304630191    图书    漫画     1    79     苏州  京东白条  2025-10-22
499  210282113  电子产品    耳机     6   399     重庆  微信支付  2025-11-17

[500 rows x 8 columns]

In [33]:
# 2.4 数据格式处理
df['订单日期'] = df['订单日期'].str.replace('.', '/')
df

           订单号  产品类别  产品名称  销售数量    单价 客户所在城市  支付方式        订单日期
0    890779946  电子产品    手机     4   499     武汉  微信支付  2025/10/22
1    200604502    图书    教材    -7   199    NaN   支付宝  2025/10/08
2    550455977    图书  考试资料     9    15     成都  京东白条  2025/10/15
3    398362082    图书   工具书     3    15     郑州   银行卡  2025/10/07
4    398362082  家居用品    枕头     7    29     深圳   银行卡  2025/12/09
5    692749116  电子产品    键盘     2  4999     长沙   支付宝  2025/11/27
6    810026086    图书    绘本     4   199    NaN   支付宝  2025/10/25
7    586845604  家居用品    枕头     2    59     长沙   银行卡  2025/12/27
8    853573823  家居用品    被子     6   129     成都   银行卡  2025/12/21
9    596348124  电子产品   钢化膜     9   299     武汉  微信支付  2025/11/09
10   964411347    图书    漫画     1    79     武汉   支付宝  2025/11/13
11   803771909  家居用品    枕头    10    59     苏州  微信支付  2025/11/13
12   678722458    食品    饼干     3    39     武汉  京东白条  2025/11/24
13   248532577    图书    传记     7   199     天津  微信支付  2025/12/16
14   740389325  电子产品    手机     3   199     南京    花呗  2025/10/13
..         ...   ...   ...   ...   ...    ...   ...         ...
485  804503060  电子产品   数据线     6   499     西安   银行卡  2025/12/21
486  964823687  家居用品    台灯     9    39     武汉   支付宝  2025/12/13
487  549431487  家居用品    被子     8    19     重庆   银行卡  2025/11/13
488  836928463  电子产品   钢化膜     4  5999     苏州  微信支付  2025/12/21
489  294493146    食品    咖啡     5   129     南京  京东白条  2025/11/04
490  802693852    食品    饼干     9    39     南京   银行卡  2025/10/08
491  379773344  家居用品    台灯     7    89     苏州   银行卡  2025/12/10
492  766422911    食品    面包     1    89     合肥  京东白条  2025/10/16
493  543570539    服装   西装裤     7    59     厦门   银行卡  2025/10/28
494  591313587    服装   连衣裙     6   129     郑州  京东白条  2025/10/11
495  781288086    服装   牛仔裤     6   499     南京   银行卡  2025/10/01
496  625679392    食品   方便面     3    25     合肥  微信支付  2025/10/05
497  511582876    图书    传记     7    99     郑州    花呗  2025/10/02
498  304630191    图书    漫画     1    79     苏州  京东白条  2025/10/22
499  210282113  电子产品    耳机     6   399     重庆  微信支付  2025/11/17

[500 rows x 8 columns]